config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :users, only: [:index]
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :short_description, presence: true
  validates :language, presence: true
  validates :level, presence: true
  validates :price, presence: true

  has_rich_text :description
  belongs_to :user

  extend FriendlyId
  friendly_id :title, use: :slugged

  def to_s
    title
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable

  has_many :courses

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    if params[:title]
      @courses = Course.where('title ILIKE ?', "%#{params[:title]}%")
   else
      @courses = Course.all
    end
  end

  def show
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:title, :description, :short_description, :language, :level, :price)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @courses = Course.all.limit(3)
    @latest_courses = Course.all.limit(3).order(created_at: :desc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.erb
<div class="card">
  <div class="card-header">
    <i class="fas fa-graduation-cap"></i> <%= link_to course.title, course_path(course) %>
  </div>
  <div class="card-body">
    <small><%= course.short_description %></small>
  </div>
  <div class="card-footer">
    <div class="text-center">
    <%= number_to_currency(course.price) %>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-md-6">
        <i class="fas fa-globe-africa"></i> <%= course.language %>
      </div>
      <div class="col-md-6 text-right">
        <i class="fas fa-signal"></i> <%= course.level %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col-md-6">
        <i class="fas fa-clock"></i> <%= course.created_at %><br>
      </div>
      <div class="col-md-6 text-right">
        <i class="fas fa-chalkboard-teacher"></i> <%= course.user %>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', course, class: 'btn btn-sm btn-primary' %>
    <%= link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning' %>
    <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %>
  </div>
</div>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-group">
    <%= f.input :title %>
    <%= f.label :description %>
    <%= f.rich_text_area :description, class: "height-auto" %>
    <small><%= f.error :description, class: "text-danger" %>
    <%= f.input :short_description %>
    <%= f.input :language, collection: ["English", "Polish", "German"] %>
    <%= f.input :level, collection: ["Beginner", "Intermediate", "Advanced"] %>
    <%= f.input :price %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<div class="card">
  <div class="card-header">
    <h2>Edit Course</h2>
  </div>
  <div class="card-body">
    <%= render 'form', course: @course %>
  </div>
</div>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Courses: <%= @courses.count %></h1>

<div class="card-columns">
  <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>

app/views/courses/new.html.erb
<div class="card">
  <div class="card-header">
    <h2>New Course</h2>
  </div>
  <div class="card-body">
    <%= render 'form', course: @course %>
  </div>
</div>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<%= link_to 'Courses', courses_path %>
/
<%= link_to @course.title, course_path(@course) %>
<p></p>
<%= render 'courses/course', course: @course %>

app/views/home/index.html.erb
<div class="jumbotron">
  <div class="display-4">
   What do you want to learn?
  </div>

  <div class="p-4">
    <div class="form-inline my-2 my-lg-0">
      <%= form_tag(courses_path, method: :get) do %>
        <div class="input-group">
          <%= text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control' %>
            <span class="input-group-append">
              <button class="btn btn-primary btn-sm" type="submit">
                <span aria-hidden="true" class="fa fa-search"></span>
              </button>
            </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="card-group">
  <div class="card card-body">
    <h1><i class="fas fa-clock"></i></h1>
    <div class="row">
      <%= Course.count %> online courses
    </div>
    <div class="row">
      Explore a variety of fresh topics
    </div>
  </div>

  <div class="card card-body">
    <h1><i class="fas fa-graduation-cap"></i></h1>
    <div class="row">
      <%= Course.distinct.count(:user_id) %> expert instructors
    </div>
    <div class="row">
      Find the right instructor for you
    </div>
  </div>

  <div class="card card-body">
    <h1><i class="fas fa-user-graduate"></i></h1>
    <div class="row">
      <%= User.count %> active students
    </div>
    <div class="row">
      Join the knowledge community
    </div>
  </div>

  <div class="card card-body">
    <h1><i class="fas fa-infinity"></i></h1>
    <div class="row">
      Lifetime access
    </div>
    <div class="row">
      Learn on your schedule
    </div>
  </div>

</div>

<hr>
<h2>Popular Courses:</h2>
<div class="card-columns">
  <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<hr>
<h2>Top Rated Courses:</h2>
<div class="card-columns">
  <% @courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<hr>
<h2>Most Recent Courses:</h2>
<div class="card-columns">
  <% @latest_courses.each do |course| %>
    <%= render 'courses/course', course: course %>
  <% end %>
</div>
<hr>

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    <%= alert %>
  </div>
<% end %> 

app/views/layouts/_footer.html.erb
<hr/>
<footer class="fixed-bottom">
  <div class="bg-dark text-white">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        Copyright
        <%= Time.now.year %>
        School-App
        <div class="row"></div>
        <div class="fa fa-envelope"></div>
        <%= mail_to 'tmtocb@gmail.com' %>
        <div class="row"></div>
      </div>
      <div class="col-md-4">
        Privacy policy
        <div class="row"></div>
        Terms and conditions
      </div>
      <div class="col-md-4">
        About us
        <div class="row"></div>
        <%= link_to 'Teach With Us', new_course_path %>
      </div>
    </div>
  </div>
</div>
</footer>
<br/>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <%= link_to 'School App', root_path, class: "navbar-brand" %>
  <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if current_user %>
      <ul class="navbar-nav mr-auto">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Home
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(courses_path) %> nav-item">
          <%= link_to courses_path, class: 'nav-link' do %>
            <div class="fa fa-graduation-cap"></div>
            Courses
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(new_course_path) %> nav-item">
          <%= link_to new_course_path, class: 'nav-link' do %>
            <div class="fa fa-plus"></div>
            New Course
          <% end %>
        </li>
        <li class="<%= 'active font-weight-bold' if current_page?(users_path) %> nav-item">
          <%= link_to users_path, class: 'nav-link' do %>
            <div class="fa fa-user"></div>
            Users
          <% end %>
        </li>
      </ul>
      <div class="form-inline my-2 my-lg-0">
        <%= form_tag(courses_path, method: :get) do %>
          <div class="input-group">
            <%= text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm' %>
            <span class="input-group-append">
              <button class="btn btn-primary btn-sm" type="submit">
                <span aria-hidden="true" class="fa fa-search"></span>
              </button>
            </span>
          </div>
        <% end %>
      </div>
      <ul class="navbar-nav mr-right">
        <li class="<%= 'active font-weight-bold' if current_page?(root_path) %> nav-item">
          <%= link_to root_path, class: 'nav-link' do %>
            <div class="fa fa-home"></div>
            Another link
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="navbarDropdown" role="button">
            <b>
              <%= current_user.email %>
            </b>
          </a>
          <div aria-labelledby="navbarDropdown" class="dropdown-menu dropdown-menu-right">
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <div class="fa fa-cog"></div>
              <b>Account settings</b>
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
              <div class="fa fa-sign-out-alt"></div>
              <b>Sign out</b>
            <% end %>
          </div>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchoolApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="Content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width; initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/alerts' %>
    <div class="container">
      <p></p>
      <%= yield %>
    </div>
    <div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/users/_user.html.erb
<div class="card">
  <div class="card-header">
    <%= user.email %>
  </div>
  <div class="card-footer">
    <div class="row">
      Signed up:
      <%= time_ago_in_words(user.created_at) %> ago
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      Sign in count:
      <%= user.sign_in_count %> 
    </div>
    <div class="row">
      Current sign in at:
      <%= user.current_sign_in_at %> 
    </div>
    <div class="row">
      Last sign in at:
      <%= user.last_sign_in_at %> 
    </div>
    <div class="row">
      Current sign in IP:
      <%= user.current_sign_in_ip %> 
    </div>
    <div class="row">
      Last sign in IP:
      <%= user.current_sign_in_ip %> 
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      Confirmed email? 
    </div>
    <div class="row">
        <% if user.confirmed_at.present? %>
          <div class="badge badge-success"> Yes </div>
        <% else %>
          <div class="badge badge-danger"> No </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="card-columns">
  <% @users.each do |user| %>
    <%= render 'users/user', user: user %>
  <% end %>
</div>